### ISSUE TITLE
阿里巴巴-新零售-CBU技术部-春招

### ISSUE THREAD

**Issue by ShuaiJunlan** [22nd-internship-group/2022-jobs#2]
【招聘岗位】Java开发工程师（实习）
【招聘部门】CBU技术部-开放平台
【工作地点】杭州
【面试方式】电话面试，先不录入系统

【部门介绍】
✅阿里巴巴1688事业部开放平台，负责阿里巴巴公司内外系统交互的中间件，专注于探索企业服务，利用人工智能技术，为企业提供智能化服务，提升企业生产效率和电商经营效率。合作伙伴有银行、物流公司、国企、各种软件提供商。团队主要业务包括有阿里巴巴开放平台(open.1688.com)，1688服务市场(fuwu.1688.com)，慧眼识货(ai.1688.com)。
✅团队代表基础技术产品包含网关、消息推送中心、授权中心等中间件，支撑百亿级别以上的日均调用量，同时支持集团内多个业务的开放与集成。团队内技术氛围很好，在这里不仅有基础类中间件产品，也有支撑各种业务快速增长的业务型产品，可以接触到最新的前沿技术、高并发高流量系统架构、微服务架构，来这里能够非常快地提高技术能力，扩展眼界。
 
【岗位描述】
✅从事中间件、商业化产品、企业开放智能工具等领域的架构设计以及核心研发工作；
✅参与业务需求的讨论，解决方案的制定以及后续的产品开发上线等任务；
✅深入理解业务，技术驱动产品发展，能够根据生态团队的业务对应输出技术规划，并且驱动产品技术落地；
✅这里不仅有成熟的通用的产品和技术，同时正在走开源之路，如果你有开源经验，更加欢迎加入～
 
【岗位要求】
✅编程能力扎实，熟悉常用的数据结构和算法；
✅熟练Java开发语言，对JVM、Web开发、缓存，分布式架构、消息中间件等技术有一定的了解；
✅具有出色的抽象能力，善于思考，能独立分析和解决问题，对技术有一定的热情；

投递链接：https://www.nowcoder.com/job/47396?jobIds=43042

**Comment by aetherrootr** [comment]
已经添加
